### ISSUE TITLE
Readme example code crashes

### ISSUE THREAD

**Issue by blooop** [hauptmech/odio_urdf#1]
The example code in the readme crashes.  This is the output:

```
Traceback (most recent call last):
  File "/home/ags/python_modules/odio_urdf/test.py", line 5, in <module>
    Link(name="link1"),
  File "/usr/local/lib/python2.7/dist-packages/odio_urdf/__init__.py", line 315, in __init__
    super().__init__(*args,**kwargs)
TypeError: super() takes at least 1 argument (0 given)
```

**Comment by hauptmech** [comment]
Thanks. Should be fixed now. Give it a try and let me know.

**Comment by blooop** [comment]
That's great, the readme example runs now. Thanks for fixing this so quickly. 
I had to modify the example code to reproduce the urdf from the tutorial, the example code was incorrectly setting the joint link names to "UNNAMED_XXX"

```
my_robot = Robot(
    Link(name="link1"),
    Link(name="link2"),
    Link("link3"),  # String arguments without keys are assumed to be 'name'
    Link(name="link4"),

    Joint("joint1", Parent(link="link1"), Child(link="link2"), type="continuous"),
    Joint("joint2",
          Parent(link="link1"),
          Child(link="link2"),
          type="continuous"  # KeyValue arguments go at the end of a call
          ),
    Joint("joint3", Parent(link="link3"), Child(link="link4"), type="continuous"),
    name="test_robot"
)
```
Thanks,
Austin

**Comment by hauptmech** [comment]
Thanks for spotting that. I have a fix but want to check it against all the example code to make sure things are consistent. Should be able to commit it in a day.
