### ISSUE TITLE
test_coman file crashes

### ISSUE THREAD

**Issue by blooop** [hauptmech/odio_urdf#3]
```
ags@xxx:~/python_modules/odio_urdf/test$ ./test_coman 
Traceback (most recent call last):
  File "coman/coman.py", line 33, in <module>
    grey =      Material(Color(rgba="0.5 0.5 0.5 1"))
  File "<string>", line 497, in __init__
NameError: global name 'self' is not defined

```

The same thing happens with python3 on my system:

```
ags@xxx:~/python_modules/odio_urdf/test/coman$ python3 coman.py
Traceback (most recent call last):
  File "coman.py", line 33, in <module>
    grey =      Material(Color(rgba="0.5 0.5 0.5 1"))
  File "<string>", line 497, in __init__
NameError: name 'self' is not defined

```

**Comment by hauptmech** [comment]
A copy-paste bug in the last commit. Fixed.

**Comment by blooop** [comment]
It works now, thanks.
